### ISSUE TITLE
Removing student from course with shared assignments

### ISSUE THREAD

**Issue by engelhamer** [eJourn-al/eJournal#284] opened 2018-08-23 12:33 UTC
# Bug report
Removing members from a course introduces complication in shared assignments.

## Expected Behavior
After a user is removed from a course that shares an assignment with another course, they should still be able to access that assignment in the other course.

## Actual Behavior
The user is presented with a 403 error stating that they do not participate in any course that is related to that assignment.

## Steps to Reproduce the Problem
1. Set up two courses with one shared assignment.
2. Remove a member from one course.
3. Try to access the shared assignment as the member you just deleted, but now in the other course.

**Comment by mjvkeulen** [comment] 2018-08-31 06:34
Using demo-db on develop (after vuex), I was not able to reproduce this by following the outlined steps.

**Comment by Larspolo** [comment] 2018-09-07 17:57
Same for me, so I am closing this issue

**Closed by Larspolo** 2018-09-07 17:57 UTC
Labels: bug, little work
