### ISSUE TITLE
Explicit page and handling for course not setup

### ISSUE THREAD

**Issue by mjvkeulen** [eJourn-al/eJournal#717] opened 2019-09-18 11:43 UTC
**Describe the solution you'd like**
Currently when a student follows a LMS link to an eJournal assignment which has not yet been setup by a staff member. The following is displayed on our error page:

> 404: Not Found
> The course you are looking for cannot be found. Most likely your teacher has not finished setting up the course.

This is still sufficiently confusing to our users, that eJournal receives blame for not working. This needs solved.

## Suggesstions
-Dedicated page, with a full explanation of the situation, and detailing the steps which are required to make this work.
- Direct notification to the eJournal team, so that action can immediately be taken

**Comment by engelhamer** [comment] 2019-09-18 11:43
Duplicate of #527.

**Closed by engelhamer** 2019-09-18 11:43 UTC
Labels: Priority: Critical, Status: Available, Type: Enhancement, Workload: Medium
